name: meson build

#on: [push, pull_request]
on:
  push:
    branches:
      - develop
      - mesonBasic
  pull_request:
    branches:
      - develop
      - mesonBasic

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    if: "github.repository == 'HaoZeke/OpenBLAS'"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build: [meson]
        fortran: [gfortran]
        openmp: [0]
        ilp64: [0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print system information
        run: |
          cat /proc/cpuinfo
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          #cache: 'pip'

      - name: Install dependencies
        run: |
          sudo apt-get install -y gfortran libtinfo5
      - name: Install packages
        run: |
          python -m pip install meson ninja
      - name: Build OpenBLAS
        run: |
          meson setup build --buildtype release
          meson compile -C build
      - name: Run tests
        run: |
          meson test -C build -v
